services:
  saas-tracker:
    build:
      context: .
      args:
        - API_KEY=${VITE_API_KEY}
        - SUPABASE_URL=${VITE_SUPABASE_URL}
        - SUPABASE_KEY=${VITE_SUPABASE_KEY}
    container_name: k5-saas-tracker
    restart: always
    ports:
      - "10.8.0.2:8086:80"
      #- "8086:80"
    networks:
      - k5-global-network

networks:
  k5-global-network:
    external: true
