services:
  saas-tracker:
    build:
      context: .
      args:
        - API_KEY=${API_KEY}
        - SUPABASE_URL=${SUPABASE_URL}
        - SUPABASE_KEY=${SUPABASE_KEY}
    container_name: k5-saas-tracker
    restart: always
    ports:
      - "10.8.0.2:8086:80"
    networks:
      - k5-global-network
    environment:
      - API_KEY=${API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}

networks:
  k5-global-network:
    external: true
